import Header from "@/components/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-100`}>
        <Header />

        <section className="flex">
          <Sidebar />

          <main className="p-8 w-full">{children}</main>
        </section>
      </body>
    </html>
  );
}
